fields = {
    "InitializeConfigEntity": "__default__,terms_of_service",
    "C1545Me": "__default__,gold_subscriber,contactable,social_profiles",
    "UserProfileEntity": "name,icon_image_url,user[__default__,gold_subscriber]",
    "LiveEpisodeDetailEntity": "__default__,episode[__default__,teachers,program[__default__,teachers],streaming_url,social_share_text,user_count,recipes[__default__,ingredients,steps],live_streamings[__default__,variants],survey_available]",
    "SpecialTalk": "__default__,started_at,ended_at,special_talk_meeting[__default__,started_at,ended_at,special_talk_attendees],special_talk_users",
    "SpecialTalkMe": "__default__,meeting_attendee[called_at,meeting,attendee]",
    "EcProduct": "__default__",
    "SubscribingEpisodesEntity": "__default__,ended_at,teachers,program[__default__,teachers],promotional_text",
    "StampSet": "__default__,icon_image_url",
    "Stamps": "__default__,text,stamps[__default__,thumbnail_image_url,image_url]",
    "TopPanelsEntity": "panels[__default__,on_air_episode[__default__,program[__default__,teachers],teachers,visibility_type,promotional_text],banner_carousel[banners[__default__,image_url]],on_air_banner[__default__,program[__default__,teachers],teachers,visibility_type,promotional_text],upcoming_episode[__default__,program[__default__,teachers],teachers,visibility_type,promotional_text],planning_episode[__default__,program[__default__,teachers],teachers,visibility_type,promotional_text]]",
    "TopPanelsSmartTvEntity": "panels[__default__,on_air_episode[__default__,program[__default__,teachers],teachers,visibility_type,promotional_text],upcoming_episode[__default__,program[__default__,teachers],teachers,visibility_type,promotional_text],archived_episodes[episodes[__default__,program[__default__,teachers],teachers,visibility_type]]]",
    "EpisodeDetailEntity": "__default__,episode[__default__,started_at,ended_at,teachers,program[__default__,teachers],streaming_url,social_share_text,archived_video_url,archive_start_offset,archive_expired_at,recipes[__default__,ingredients,steps],archive_streamings[__default__,variants],special_videos[__default__,streaming_url,max_width,max_height,variants],planning_text,promotional_text,archive_comments_url]",
    "TeachersEpisodeEntity": "__default__,ended_at,teachers,program[__default__,teachers],promotional_text",
    "SubscriptionSynchronizationsEntity": "__default__,user[__default__,gold_subscriber],message,initial_gold_subscriber,new_gold_subscriber",
    "CampaignEpisode": "__default__,started_at,ended_at,program[__default__,teachers],streaming_url,archived_video_url,archive_start_offset,user_count,recipes[__default__,ingredients,steps],streaming_variant_streams,archive_variant_streams,card_thumbnail_image_url,card_thumbnail_text",
    "ArchivePanelsEntity": "panels[__default__,banner_carousel[banners[__default__,image_url]],episode_digests,ended_episodes[__default__,visibility_type,program[__default__,teachers],teachers,promotional_text],free_archived_episodes[episodes[__default__,visibility_type,program[__default__,teachers],teachers,promotional_text]],gold_archived_programs[programs[__default__,teachers]]]",
    "EpisodesEntity": "__default__,teachers,program[__default__,teachers],promotional_text",
    "Program": "__default__,teachers",
    "EcReceiptEntity": "__default__,ec_order[__default__,ec_product],payment_url",
    "ChallengePanels": "topics[__default__,certified_episodes[__default__,started_at,thumbnail_url,score]]",
}
